### ISSUE TITLE
pyrap and python-casacore conflict

### ISSUE THREAD

**Issue by bmerry** [radio-astro-debian/python-casacore-debian#1]
python-casacore and pyrap both try to install Python modules in the pyrap namespace, leading to errors from dpkg.

An ideal solution might be to split python-casacore into two binary packages: one that installs the files in the casacore directory, and one that provides the backwards-compatibility files in the pyrap directory. Then one could either install python-casacore + pyrap or python-casacore + python-casacore-compat, depending on whether you want the pyrap interface to be provided by pyrap or python-casacore.

Failing that, a Conflicts: header in the deb would be nice.

**Comment by o-smirnov** [comment]
I thought python-casacare was quite simply the new name for pyrap. Can't we just kill off the pyrap package -- or are there any changes in the API between them?

**Comment by bmerry** [comment]
I don't know if there are API changes or not, but one difference is that python-casacore depends on casacore 2.x. There could be issues if one mixes casacore 1.x and casacore 2.x in the same process - I don't know if that would happen with anything in the repository at the moment. Once everything is converted to casacore 2.x it probably makes sense to kill off pyrap, and have python-casacore use a Replaces: or whatever the correct Debian header is to supersede it.

**Comment by gijzelaerr** [comment]
best solution is to switch all depending programs to CASACORE 2.0. The changes are minimal, the thing that causes the most compilation errors is the move of the header files into the casacore directory. This is a very easy fix. 

https://github.com/casacore/casacore/blob/master/CHANGES.md

**Comment by gijzelaerr** [comment]
moving discussion here: https://github.com/radio-astro/packaging/issues/13
